/*
 * Copyright 2026 Boris Tarelkin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ru.max.botapi.examples;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import ru.max.botapi.client.MaxBotAPI;
import ru.max.botapi.client.MaxUploadAPI;
import ru.max.botapi.longpolling.MaxLongPollingConsumer;
import ru.max.botapi.model.FileAttachmentRequest;
import ru.max.botapi.model.MediaRequestPayload;
import ru.max.botapi.model.MessageCreatedUpdate;
import ru.max.botapi.model.NewMessageBody;
import ru.max.botapi.model.UploadEndpoint;
import ru.max.botapi.model.UploadType;
import ru.max.botapi.model.UploadedInfo;

/**
 * A bot that demonstrates file upload functionality.
 *
 * <p>When the user sends the command {@code /upload}, the bot creates a small
 * text file, uploads it to the MAX platform, and sends it back to the chat.
 * This demonstrates the two-step upload flow:</p>
 * <ol>
 *   <li>Obtain an upload URL via {@code POST /uploads}</li>
 *   <li>Upload the file to that URL</li>
 *   <li>Send a message with the uploaded file token as an attachment</li>
 * </ol>
 *
 * <p>Usage:</p>
 * <pre>
 * export MAX_BOT_TOKEN="your-bot-token"
 * ./gradlew :max-bot-api-examples:run -PmainClass=ru.max.botapi.examples.FileUploadBot
 * </pre>
 */
public final class FileUploadBot {

    private FileUploadBot() {
    }

    /**
     * Entry point for the file upload bot.
     *
     * @param args command-line arguments (unused)
     */
    public static void main(String[] args) {
        String token = System.getenv("MAX_BOT_TOKEN");
        if (token == null || token.isBlank()) {
            System.err.println("Set the MAX_BOT_TOKEN environment variable.");
            System.exit(1);
        }

        MaxBotAPI api = MaxBotAPI.create(token);

        try (MaxUploadAPI uploadApi = new MaxUploadAPI();
             MaxLongPollingConsumer consumer = MaxLongPollingConsumer.builder()
                     .api(api)
                     .handler(update -> {
                         if (update instanceof MessageCreatedUpdate msg) {
                             String text = msg.message().body().text();
                             if ("/upload".equals(text)) {
                                 handleUploadCommand(api, uploadApi, msg);
                             }
                         }
                     })
                     .build()) {

            consumer.start();
            System.out.println("FileUploadBot is running. Send /upload to test. Press Ctrl+C to stop.");

            Thread.currentThread().join();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private static void handleUploadCommand(MaxBotAPI api, MaxUploadAPI uploadApi,
                                             MessageCreatedUpdate msg) {
        Long chatId = msg.message().recipient().chatId();
        if (chatId == null) {
            return;
        }
        try {
            // Step 1: Create a temporary file
            Path tempFile = Files.createTempFile("max-bot-example-", ".txt");
            Files.writeString(tempFile, "Hello from MAX Bot API!\n"
                    + "This file was generated by FileUploadBot.\n"
                    + "Timestamp: " + System.currentTimeMillis(),
                    StandardCharsets.UTF_8);

            // Step 2: Get upload URL
            UploadEndpoint endpoint = api.getUploadUrl(UploadType.FILE).execute();

            // Step 3: Upload the file
            UploadedInfo uploaded = uploadApi.upload(endpoint.url(), tempFile, "example.txt");

            // Step 4: Send message with uploaded file
            FileAttachmentRequest fileAttachment =
                    new FileAttachmentRequest(new MediaRequestPayload(uploaded.token()));

            NewMessageBody body = new NewMessageBody(
                    "Here is your file:",
                    List.of(fileAttachment),
                    null, null, null
            );

            api.sendMessage(body).chatId(chatId).execute();

            // Clean up temp file
            Files.deleteIfExists(tempFile);

        } catch (IOException e) {
            System.err.println("I/O error during file upload: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Failed to upload file: " + e.getMessage());
        }
    }
}
